---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-webhook-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgAbsRAVNYARBFbZMK4mzuT84ZkRdIEOX5z0cWaBnxRp3FDvQGa8/hcsPYyDkAMUwUa60NB+OyQNRvAAX/eCYU+bSrm59B822WwoS+adTkxGieo/MqtTYJXhkC4S2qSwq06rtTzbLvlyBg9pvq5K+75S03tQ8AISHfMP2EgZ0f0BBSYRvgv9FchexcmIrGpM65GhSz83m+bm1qX51RTgCtob0Kn7r+OmPaK1bPEseRMm8OLccFCFhf7d+gX8mWPCyEWTFAFlbGrcYFldRPzcji2G+u14CNRVs7f1EILU9+EdLg7p2KV+Tih2xB4dXmxWxIE2+ztokN1qCclYGC0pyfgevDzf8uHu075Gp4S1AfpxO/B2iyyogmYk6eppiTHly9x5UFBxzbNsABCKq6Me+FXgT+yRvxar9EHFBZelfxpTCD0pO1ajSvs9bWWRQ1+bJQPFOKUZPEHIJUM3Dfutb7TP7FW7MerTbvSu8Xwd9lkzMApB+Zn+e1WroRZbxDvG0Tx4Zad1LQBVVfHlEtNNiyrR1j0IiY01nOdrpX/pTxQ93PW/ZcqO3eL63X4Pq8d2h7fNsbKGujexk0LkuKIMw1GCsNMe2AGGGeNxoH1bgeW6N4FtqzUFTpTbEN1FtaLCRF839z0qGUSlEPNviAe6yQuV+XU46kqFAfwXam/pP4l9DtofKxWOwZLgcTi5UACD7VZ2HjUAITwudZAS5apHOpgpMsc2xFC8htsGu6hokYUPYYM8oa5BvWfj+Fj09azT3lLgX5J8SoUzbB50129T9yohN/V/dpeGQaaiGXXcD6cEYSeZrnXlAkJ+upKMflJIyPph8DXGgFDnzO1oTegJyxjD7nwNmXKkOuqI
  template:
    metadata:
      creationTimestamp: null
      name: discord-webhook-url
      namespace: flux-system
