apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-test
  namespace: nginx-test
spec:
  secretName: nginx-test-tls
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - nginx-test.zonedev.be
