apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "33.x"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 12h
  values:
    globalArguments:
      - "--global.sendanonymoususage=false"
      - "--global.checknewversion=false"

    additionalArguments:
      - "--serversTransport.insecureSkipVerify=true"
      - "--log.level=DEBUG"

    deployment:
      enabled: true
      replicas: 2
      annotations: {}
      podAnnotations: {}
      additionalContainers: []
      initContainers: []

    nodeSelector:
      agent: "true"

    ports:
      web:
        redirections:
          to: websecure
          priority: 10
          schema: https
          permanent: true
      websecure:
        tls:
          enabled: true

    providers:
      kubernetesCRD:
        enabled: true
        ingressClass: traefik-external
        allowExternalNameServices: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        publishedService:
          enabled: false

    rbac:
      enabled: true

    service:
      enabled: true
      type: LoadBalancer
      annotations:
        kube-vip.io/loadBalancerIPs: "10.8.8.70"
      spec:
        loadBalancerIP: 10.8.8.70
